### ISSUE TITLE
Does calphy do minimization/relaxation?

### ISSUE THREAD

**Issue by ZAhra-Rjz** [srmnitc/calphy-publication-examples#1]
Hi,
I have a technical question.
 I want to calculate free energy for my structure, but first, I need to minimize my structure. I did not find any commands for it in calphy documentation. 
Can you tell me how calphy does minimization? Or is there any command for it?

Thank you

**Comment by srmnitc** [comment]
@ZAhra-Rjz It is not really minimization, but the equilibriation of the structure. The very first step that calphy does is to run an equilibriation routine at the input temperature and pressure. This run is auto terminated once the desired pressure is achieved. You can see information about this from the calphy.log file. 

In case of liquid as the reference state, a melting MD run is performed before the equilibriation routine.

**Comment by ZAhra-Rjz** [comment]
Thank you for your answer. 
Yes, I see the calphy.log file. 
but which command exactly does the equilibriation of the structure? I'm so sorry for my question. I am trying to understand commands in the input script.
For example in this script:
calculations:
- element: Fe
  lattice: BCC
  lattice_constant: 2.884
  mass: 55.845
  md:
    barostat_damping: 0.1
    equilibration_control: nose_hoover
    thermostat_damping: 0.1
    timestep: 0.001
  mode: fe
  n_equilibration_steps: 10000
  n_iterations: 1
  n_switching_steps: 25000
  pair_coeff: '* * ../potentials/Fe.eam'
  pair_style: eam
  pressure: 0.0
  queue:
    commands:
    - conda activate calphy
    cores: 4
    scheduler: local
  reference_phase: solid
  repeat:
  - 5
  - 5
  - 5
  temperature: 100.0
  tolerance:
    pressure: 1
Does "equilibration_control: nose_hoover" do the equilibration or "n_equilibration_steps: 10000"?  Or many all "md" part for equilibration purposes?
